[package]
name = "dunsthist"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
ratatui = { version = "0.29.0", features = ["macros", "palette", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
