[package]
name = "dunsthist"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
cursive = "0.21.1"
cursive-hjkl = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
